CREATE TABLE blogful_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    date_published TIMESTAMP DEFAULT now() NOT NULL,
    content TEXT
); 

/*
INSERT INTO shopping_list (title, content, date_published)
VALUES
    ('blog title 1', 'content 1' , now() - '21 days'::INTERVAL),
    ('blog title 2', 'content 2' , now() - '21 days'::INTERVAL),
    ('blog title 3', 'content 3' , now() - '21 days'::INTERVAL),
    ('blog title 4', 'content 4' , now() - '21 days'::INTERVAL),
    ('blog title 5', 'content 5' , now() - '9 days'::INTERVAL),
    ('blog title 6', 'content 6' , now() - '9 days'::INTERVAL),
    ('blog title 7', 'content 7' , now() - '9 days'::INTERVAL),
    ('blog title 8', 'content 8' , now() - '9 days'::INTERVAL),
    ('blog title 9', 'content 9' , now() - '9 days'::INTERVAL),
    ('blog title 10', 'content 10' , now() - '5 days'::INTERVAL),
    ('blog title 11', 'content 11' , now() - '5 days'::INTERVAL),
    ('blog title 12', 'content 12' , now() - '5 days'::INTERVAL),
    ('blog title 13', 'content 13' , now() - '5 days'::INTERVAL),
    ('blog title 14', 'content 14' , now() - '4 days'::INTERVAL),
    ('blog title 15', 'content 15' , now() - '4 days'::INTERVAL),
    ('blog title 16', 'content 16' , now() - '4 days'::INTERVAL),
    ('blog title 17', 'content 17' , now() - '4 days'::INTERVAL),
    ('blog title 18', 'content 18' , now() - '4 days'::INTERVAL),
    ('blog title 19', 'content 19' , now() - '4 days'::INTERVAL),
    ('blog title 20', 'content 20' , now() - '1 days'::INTERVAL)
;
*/